### ISSUE TITLE
Dealing with post-CR documents

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec-w3c-auto-publish#18]
I assume this action will trigger an echidna publication even once a document has reached CR, which will then fail unless it is somehow marked as an editorial update.

It would ideal if the action could take this situation into account, e.g. by:
* not auto-publishing once a doc has reached CR
* accepting input one way or another to indicate that an editorial CR push is intended (although that might be too much of a footgun)

**Comment by dontcallmedom** [comment]
with the new process document, this can be handled fairly easily by always publishing a CRD (which is always allowed if you've reached CR a first time). This would still need to handle the case where a doc is a PR or a Rec.

**Comment by sidvishnoi** [comment]
Would it be possible if instead of detecting whether document can be published, users disable deployment with a flag in action.yml? There is https://github.com/sidvishnoi/spec-prod/ which allows "not deploying" (by not passing echidna token).

I plan to deprecate this action in favor of spec-prod. If manually asking not to deploy is not preferable, I can support it in spec-prod instead.

**Comment by dontcallmedom** [comment]
my sense is that anything that requires manual action will be missed most of the time, so ideally, the automation tools should do their best to do the right thing.

To me, this means that the spec-prod action (great to hear about it, sounds like a fantastic idea) should adjust its operations based on the status of a spec:
* if TR spec is FPWD, republish as WD by default (without requiring a change in the echidna manifest)
* if TR spec is CR, republish as CRD by default
* if TR is PR or Rec, stop trying to republish

**Comment by sidvishnoi** [comment]
Closing in favor of https://github.com/w3c/spec-prod/issues/13
